<div data-bind="scope: 'pronko-component'">
    <h2 data-bind="text: title"></h2>
</div>

<script type="text/x-magento-init">
    {
        "*" : {
             "Magento_Ui/js/core/app" : {
                   "components" : {
                        "pronko-component": {
                             "component" : "Tuandz_UI/js/component",
                             "title" : "Hello World"
                        }
                   }
             }
        }
    }
</script>
